Update cloudbuild1.yaml

diff --git a/cloudbuild1.yaml b/cloudbuild1.yaml
--- a/cloudbuild1.yaml
+++ b/cloudbuild1.yaml
@@ -3,9 +3,9 @@ substitutions:
   _COMPOSER_REGION: asia-south1
   _COMPOSER_ENV_NAME: arflow-hasim
   _ROLLBACK: 'false'
-  _SEVERITY: MEDIUM
-  _SEVERITY1: HIGH
-  _SEVERITY2: CRITICAL
+#   _SEVERITY: MEDIUM
+#   _SEVERITY1: HIGH
+#   _SEVERITY2: CRITICAL
   
 # Access the id_github file from Secret Manager, and setup SSH
 steps:
@@ -35,68 +35,68 @@ steps:
     - name: 'ssh'
       path: /root/.ssh
 
-  - name: gcr.io/cloud-builders/gcloud
-    entrypoint: /bin/bash
-    args:
-     - -c
-     - |
-       gcloud artifacts repositories set-cleanup-policy my-image6 \
-       --project=fg-dev-host \
-       --location=us \
-       --policy=policy.json \
+#   - name: gcr.io/cloud-builders/gcloud
+#     entrypoint: /bin/bash
+#     args:
+#      - -c
+#      - |
+#        gcloud artifacts repositories set-cleanup-policy my-image6 \
+#        --project=fg-dev-host \
+#        --location=us \
+#        --policy=policy.json \
 
  # Build the image
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-t', 'gcr.io/fg-dev-host/my-image6:v1.7', '.']
 
-# Check the vulnerabilities and exit if it meets severity level
-  - id: scan
-    name: gcr.io/cloud-builders/gcloud
-    entrypoint: /bin/bash
-    args:
-     - -c
-     - |
-       gcloud artifacts docker images scan 'gcr.io/fg-dev-host/my-image6:v1.7' \
-       --format='value(response.scan)' > /workspace/docdags/scan_id.txt
+# # Check the vulnerabilities and exit if it meets severity level
+#   - id: scan
+#     name: gcr.io/cloud-builders/gcloud
+#     entrypoint: /bin/bash
+#     args:
+#      - -c
+#      - |
+#        gcloud artifacts docker images scan 'gcr.io/fg-dev-host/my-image6:v1.7' \
+#        --format='value(response.scan)' > /workspace/docdags/scan_id.txt
        
-  - id: severity check2
-    name: gcr.io/cloud-builders/gcloud
-    entrypoint: /bin/bash
-    args:
-     - -c
-     - | 
-       gcloud artifacts docker images list-vulnerabilities \
-        $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
-        | if grep -Fxq $_SEVERITY2 
-          then echo 'Failed vulnerability check - CRITICAL'
-          exit 1 
-          fi
+#   - id: severity check2
+#     name: gcr.io/cloud-builders/gcloud
+#     entrypoint: /bin/bash
+#     args:
+#      - -c
+#      - | 
+#        gcloud artifacts docker images list-vulnerabilities \
+#         $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
+#         | if grep -Fxq $_SEVERITY2 
+#           then echo 'Failed vulnerability check - CRITICAL'
+#           exit 1 
+#           fi
           
-  - id: severity check1
-    name: gcr.io/cloud-builders/gcloud
-    entrypoint: /bin/bash
-    args:
-     - -c
-     - | 
-       gcloud artifacts docker images list-vulnerabilities \
-        $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
-        | if grep -Fxq $_SEVERITY1
-          then echo 'Failed vulnerability check - HIGH'
-          exit 1 
-          fi
+#   - id: severity check1
+#     name: gcr.io/cloud-builders/gcloud
+#     entrypoint: /bin/bash
+#     args:
+#      - -c
+#      - | 
+#        gcloud artifacts docker images list-vulnerabilities \
+#         $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
+#         | if grep -Fxq $_SEVERITY1
+#           then echo 'Failed vulnerability check - HIGH'
+#           exit 1 
+#           fi
 
-  - id: severity check
-    name: gcr.io/cloud-builders/gcloud
-    entrypoint: /bin/bash
-    args:
-     - -c
-     - | 
-       gcloud artifacts docker images list-vulnerabilities \
-        $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
-        | if grep -Fxq $_SEVERITY 
-          then echo 'Failed vulnerability check - MEDIUM'
-          exit 1 
-          fi
+#   - id: severity check
+#     name: gcr.io/cloud-builders/gcloud
+#     entrypoint: /bin/bash
+#     args:
+#      - -c
+#      - | 
+#        gcloud artifacts docker images list-vulnerabilities \
+#         $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
+#         | if grep -Fxq $_SEVERITY 
+#           then echo 'Failed vulnerability check - MEDIUM'
+#           exit 1 
+#           fi
   
 # Push the image to GCR
   - name: 'gcr.io/cloud-builders/docker'
